package me.garfieldcmix.testplugin.commands;

import me.garfieldcmix.gfmcommandcreator.gfmcommand.GfmHeadCommand;
import me.garfieldcmix.gfmcommandcreator.gfmcommand.GfmSubCommand;

public class TestTabcomplete {
	public static GfmHeadCommand gfmTabcomplete() {
		return (GfmHeadCommand) new GfmHeadCommand.builder()
				.setName("gfmtabcomplete")
				.addTabCompleteArg("sub1tab1", "sub1tab2", "sub1tab3")
				.setGfmCommandHandler((commandSender, strings) -> false)
				.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
						.setName("sub1")
						.addTabCompleteArg("sub2tab1", "sub2tab2", "sub2tab3")
						.setGfmCommandHandler((commandSender, strings) -> false)
						.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
								.setName("sub2")
								.addTabCompleteArg("sub3tab1", "sub3tab2", "sub3tab3")
								.setGfmCommandHandler((commandSender, strings) -> false)
								.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
										.setName("sub3")
										.addTabCompleteArg("sub4tab1", "sub4tab2", "sub4tab3")
										.setGfmCommandHandler((commandSender, strings) -> false)
										.build()
								)
								.build()
						)
						.build()
				)
				.build();
	}

	public static GfmHeadCommand gfmDefaultTabcomplete() {
		return (GfmHeadCommand) new GfmHeadCommand.builder()
				.setName("gfmdefaulttabcomplete")
				.setGfmCommandHandler((commandSender, strings) -> false)
				.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
						.setName("sub1h")
						.setGfmCommandHandler((commandSender, strings) -> false)
						.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
								.setName("sub11")
								.setGfmCommandHandler((commandSender, strings) -> false)
								.build()
						)
						.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
								.setName("sub21")
								.setGfmCommandHandler((commandSender, strings) -> false)
								.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
										.setName("sub12")
										.setGfmCommandHandler((commandSender, strings) -> false)
										.build()
								)
								.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
										.setName("sub22")
										.setGfmCommandHandler((commandSender, strings) -> false)
										.build()
								)
								.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
										.setName("sub32")
										.setGfmCommandHandler((commandSender, strings) -> false)
										.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
												.setName("sub13")
												.setGfmCommandHandler((commandSender, strings) -> false)
												.build()
										)
										.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
												.setName("sub23")
												.setGfmCommandHandler((commandSender, strings) -> false)
												.build()
										)
										.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
												.setName("sub33")
												.setGfmCommandHandler((commandSender, strings) -> false)
												.build()
										)
										.build()
								)
								.build()
						)
						.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
								.setName("sub31")
								.setGfmCommandHandler((commandSender, strings) -> false)
								.build()
						)
						.build()
				)
				.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
						.setName("sub2h")
						.setGfmCommandHandler((commandSender, strings) -> false)
						.build()
				)
				.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
						.setName("sub3h")
						.setGfmCommandHandler((commandSender, strings) -> false)
						.build()
				)
				.build();
	}

	public static GfmHeadCommand gfmPermissionTabcomplete() {
		return (GfmHeadCommand) new GfmHeadCommand.builder()
				.setName("gfmpermissiontabcomplete")
				.setGfmCommandHandler((commandSender, strings) -> false)
				.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
						.isPermissionBlockTabComplete(true)
						.setName("sub1h")
						.setPermission("testplugin.commands.sub1")
						.setGfmCommandHandler((commandSender, strings) -> false)
						.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
								.isPermissionBlockTabComplete(true)
								.setName("sub11")
								.setPermission("testplugin.commands.sub1")
								.setGfmCommandHandler((commandSender, strings) -> false)
								.build()
						)
						.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
								.isPermissionBlockTabComplete(true)
								.setName("sub21")
								.setPermission("testplugin.commands.sub2")
								.setGfmCommandHandler((commandSender, strings) -> false)
								.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
										.isPermissionBlockTabComplete(true)
										.setName("sub12")
										.setPermission("testplugin.commands.sub1")
										.isPermissionBlockGfmSubCommands(true)
										.setGfmCommandHandler((commandSender, strings) -> false)
										.build()
								)
								.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
										.isPermissionBlockTabComplete(true)
										.setName("sub22")
										.setPermission("testplugin.commands.sub2")
										.setGfmCommandHandler((commandSender, strings) -> false)
										.build()
								)
								.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
										.isPermissionBlockTabComplete(true)
										.setName("sub32")
										.setPermission("testplugin.commands.sub3")
										.setGfmCommandHandler((commandSender, strings) -> false)
										.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
												.isPermissionBlockTabComplete(true)
												.setName("sub13")
												.setPermission("testplugin.commands.sub1")
												.setGfmCommandHandler((commandSender, strings) -> false)
												.build()
										)
										.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
												.isPermissionBlockTabComplete(true)
												.setName("sub23")
												.setPermission("testplugin.commands.sub2")
												.setGfmCommandHandler((commandSender, strings) -> false)
												.build()
										)
										.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
												.isPermissionBlockTabComplete(true)
												.setName("sub33")
												.setPermission("testplugin.commands.sub3")
												.setGfmCommandHandler((commandSender, strings) -> false)
												.build()
										)
										.build()
								)
								.build()
						)
						.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
								.isPermissionBlockTabComplete(true)
								.setName("sub31")
								.setPermission("testplugin.commands.sub3")
								.setGfmCommandHandler((commandSender, strings) -> false)
								.build()
						)
						.build()
				)
				.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
						.isPermissionBlockTabComplete(true)
						.setName("sub2h")
						.setPermission("testplugin.commands.sub2")
						.setGfmCommandHandler((commandSender, strings) -> false)
						.build()
				)
				.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
						.isPermissionBlockTabComplete(true)
						.setName("sub3h")
						.setPermission("testplugin.commands.sub3")
						.setGfmCommandHandler((commandSender, strings) -> false)
						.build()
				)
				.build();
	}

	public static GfmHeadCommand gfmPlayerTabcomplete() {
		return (GfmHeadCommand) new GfmHeadCommand.builder()
				.setName("gfmplayertabcomplete")
				.isTabCompletePlayer(true)
				.setGfmCommandHandler((commandSender, strings) -> false)
				.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
						.setName("sub1")
						.isTabCompletePlayer(true)
						.setGfmCommandHandler((commandSender, strings) -> false)
						.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
								.setName("sub2")
								.isTabCompletePlayer(true)
								.setGfmCommandHandler((commandSender, strings) -> false)
								.addGfmSubCommand((GfmSubCommand) new GfmSubCommand.builder()
										.setName("sub3")
										.isTabCompletePlayer(true)
										.setGfmCommandHandler((commandSender, strings) -> false)
										.build()
								)
								.build()
						)
						.build()
				)
				.build();
	}


}
